app:
  build: .
  restart: always

nginx:
  image: 'jwilder/nginx-proxy'
  restart: always
  container_name: nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - /etc/letsencrypt:/etc/letsencrypt
  ports:
    - "80:80"
    - "443:443"

data:
  image: 'busybox:ubuntu'
  command: /bin/true
  volumes:
    - '/containers_backup'