version: '2'
services:
  app:
    image: node:argon
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "3002:3002"
      - "9000:9000"
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - PORT=9000