app:
  image: node:argon
  volumes:
    - .:/app
  working_dir: /app
  expose:
    - "3000"
    - "3001"
  command: /bin/bash
  stdin_open: true
  tty: true
  environment:
    - VIRTUAL_HOST=nunpress.app
    - VIRTUAL_PORT=3001
  volumes_from:
    - data


nginx:
  extends:
    file: base.yml
    service: nginx
  environment:
    - DEFAULT_HOST=nunpress.app